# Generated by Django 4.0.3 on 2024-07-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='correctly_pronounced_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_words_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
