# Generated by Django 4.0.3 on 2024-07-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_resetpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='words_to_focus',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
